trigger:
  batch: true
  branches:
    include:
      - main
  tags:
    include:
      - "*.*.*"

parameters:
  - name: versionOverride
    displayName: "[OPTIONAL] Build/deploy version override"
    type: string
    default: ' '

variables:
  # Debugging
  System.Debug: true

resources:
  repositories:
    - repository: templates
      type: git
      name: opdrachten/templates
      ref: main

extends:
  template: pipelines/aks/template.yaml@templates
  parameters:
    name: verkeersvergunningen-backend
    ${{ if ne(parameters.versionOverride, ' ') }}:
      version: ${{ parameters.versionOverride }}
    build:
      producedImages:
      - opdrachten/verkeersvergunningen
    dev:
      pool: Opdrachten
      namespace: ns-ccc-opdr-ont-01-verkeersvergunningen
      kubernetesServiceConnection: SCN-K8S-ns-ccc-opdr-ont-01-verkeersvergunningen
      preSteps:
        - script: helm uninstall backend -n ns-ccc-opdr-ont-01-verkeersvergunningen || true
    test:
      pool: Opdrachten
      namespace: ns-ccc-opdr-tst-01-verkeersvergunningen
      kubernetesServiceConnection: SCN-K8S-ns-ccc-opdr-tst-01-verkeersvergunningen
      preSteps:
        - script: helm uninstall backend -n ns-ccc-opdr-tst-01-verkeersvergunningen || true
    acc:
      pool: Opdrachten
      namespace: ns-ccc-opdr-acc-01-verkeersvergunningen
      kubernetesServiceConnection: SCN-K8S-ns-ccc-opdr-acc-01-verkeersvergunningen
      preSteps:
        - script: helm uninstall backend -n ns-ccc-opdr-acc-01-verkeersvergunningen || true
    prod:
      pool: Opdrachten
      namespace: ns-ccc-opdr-prd-01-verkeersvergunningen
      kubernetesServiceConnection: SCN-K8S-ns-ccc-opdr-prd-01-verkeersvergunningen
      preSteps:
        - script: helm uninstall backend -n ns-ccc-opdr-prd-01-verkeersvergunningen || true